# Documentation: http://docs.travis-ci.com/user/languages/julia/
notifications:
  email: false

language: julia

os:
  - linux
#  - osx
#  - windows

julia:
  - 1.5
  - nightly

cache:
  directories:
  - $HOME/.julia/artifacts

before_script:
  - julia --color=yes -e 'using Pkg; pkg"dev https://github.com/MikeInnes/XLATools.jl"'
  - julia --color=yes -e 'using Pkg; pkg"dev https://github.com/MikeInnes/Poirot.jl"'
  # - julia --color=yes -e 'using Pkg; pkg"dev IRTools Zygote"'
  - julia --color=yes -e 'using Pkg; pkg"precompile"'

script:
  - JIVE_PROCS=auto julia --color=yes -e 'using Pkg; Pkg.test()'
