# Documentation: http://docs.travis-ci.com/user/languages/julia/
notifications:
  email: false

language: julia

os:
  - linux

julia:
  - 1.1
  - nightly

before_script:
  - julia --color=yes -e 'using Pkg; pkg"dev OrdinaryDiffEq"'
  - julia --color=yes -e 'using Pkg; pkg"dev Zygote IRTools"'
  - julia --color=yes -e 'using Pkg; pkg"dev https://github.com/JuliaDebug/JuliaInterpreter.jl.git"'
  - julia --color=yes -e 'using Pkg; pkg"dev https://github.com/JuliaDebug/Debugger.jl.git"'
  - julia --color=yes -e 'using Pkg; pkg"add https://github.com/bicycle1885/TableReader.jl.git"'
  - julia --color=yes -e 'using Pkg; pkg"precompile"'

script:
  - JIVE_PROCS=auto julia --color=yes -e 'using Pkg; Pkg.test()'
