name = "TestJulia11"
uuid = "d5289bb2-1f13-11e9-3afd-9f5bd124b26f"
authors = ["WooKyoung Noh <wookay.noh@gmail.com>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Jive = "ba5e3d4b-8524-549f-bc71-e76ad9e9deed"
DiffEqFlux = "aae7a2af-3d4f-5e19-a356-7da93b79d9d0"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
IRTools = "7869d1d1-7146-5819-86e3-90919afe41df"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
TerminalRegressionTests = "98bfdc55-cc95-5876-a49a-74609291cbe0"
VT100 = "7774df62-37c0-5c21-b34d-f6d7f98f54bc"
DiffEqSensitivity = "41bf760c-e81c-5289-8e54-58b1f1f8abe2"
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"

[targets]
test = ["Test", "Jive", "DiffEqFlux", "Flux", "Zygote", "IRTools", "LinearAlgebra", "TerminalRegressionTests", "VT100", "DiffEqSensitivity", "DiffEqCallbacks", "OrdinaryDiffEq"]
