name = "TestJulia11"
uuid = "d5289bb2-1f13-11e9-3afd-9f5bd124b26f"
authors = ["WooKyoung Noh <wookay.noh@gmail.com>"]
version = "0.1.0"

[extras]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Jive = "ba5e3d4b-8524-549f-bc71-e76ad9e9deed"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"

[targets]
test = ["Printf", "Dates", "TOML", "SparseArrays", "LinearAlgebra", "InteractiveUtils", "Test", "Random",
        "Jive", "MacroTools"]

[compat]
Jive = "0.3"
MacroTools = "0.5"
