name = "TestJulia11"
uuid = "d5289bb2-1f13-11e9-3afd-9f5bd124b26f"
authors = ["WooKyoung Noh <wookay.noh@gmail.com>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Jive = "ba5e3d4b-8524-549f-bc71-e76ad9e9deed"
ASTInterpreter2 = "e6d88f4b-b52a-544c-a8d3-7a4f12cb39c3"
DebuggerFramework = "67417a49-6d77-5db2-98c7-c13144130cd2"
DiffEqFlux = "aae7a2af-3d4f-5e19-a356-7da93b79d9d0"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
IRTools = "7869d1d1-7146-5819-86e3-90919afe41df"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[targets]
test = ["Test", "Jive", "ASTInterpreter2", "DebuggerFramework", "DiffEqFlux", "Flux", "Zygote", "IRTools", "LinearAlgebra"]
