name = "TestJulia11"
uuid = "d5289bb2-1f13-11e9-3afd-9f5bd124b26f"
authors = ["WooKyoung Noh <wookay.noh@gmail.com>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Jive = "ba5e3d4b-8524-549f-bc71-e76ad9e9deed"
ASTInterpreter2 = "e6d88f4b-b52a-544c-a8d3-7a4f12cb39c3"
DebuggerFramework = "67417a49-6d77-5db2-98c7-c13144130cd2"
DiffEqFlux = "aae7a2af-3d4f-5e19-a356-7da93b79d9d0"

[targets]
test = ["Test", "Jive", "ASTInterpreter2", "DebuggerFramework", "DiffEqFlux"]
